title: Můj první Jekyll web
description: Teď se učím, jak funguje Jekyll
permalink: /:slugified_categories/:title/

date_format: "%d. %m. %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
